### ISSUE TITLE
1px width elements as .0625rem disappear in some browers

### ISSUE THREAD

**Issue by dominicwhittle** [cuth/postcss-pxtorem#15]
QUESTION

1px widths (borders etc) specced in rem can disappear completely in some browsers (Chrome) when users zoom out. This isn't a bug with pxtorem obviously, but some possible strategies for dealing with it might be: 

- add prop_black_list for `prop_black_list: ['border', 'border-width']` type use
- add a min-size to convert (going to mess with things like letter-spacing, so bad idea) 

I realise that there is already a `selector_black_list` but that's not quite what I want. 

***

Honestly, if this is a just me issue, then I might be best writing a postcss module to run afterwards and convert back any .0625rem (1px) values to px.

**Comment by dominicwhittle** [comment]
I've just noticed from [here](https://github.com/cuth/postcss-pxtorem/issues/5#issuecomment-1145113970) that mixed case and uppercase px values are ignored and not converted:

````
.myDiv {
  border: 1Px solid; // won't be converted
  border-width: 3PX; // also won't be converted
}
````

This does what I need — if a little hacky. Apologies if I missed this in the docs.

**Comment by cuth** [comment]
Thanks, you are correct about the border width being an issue. My personal use only consists of a white list of font related properties so I am not running into the same issues as others. Thanks for bringing this to my attention.

The property black list is a good idea and I'm debating whether I should add it if it won't slow down the process.

For now, I've added a paragraph on the README to show people how to use the uppercase px units to ignore specific declarations.

**Comment by dominicwhittle** [comment]
Thanks!

**Comment by kerryj89** [comment]
If anyone else landed here from Google you can use the `minPixelValue` option.

```
minPixelValue: 1.01 // 1px stays as 1px. 1.1px, 1.5px, and up converts to rem equivalent. If you don't want _any_ 1px unit just set minPixelValue to 2.
```
