### ISSUE TITLE
option to skip border: 1px

### ISSUE THREAD

**Issue by sylvainbaronnet** [cuth/postcss-pxtorem#17]
hello,

border with 1px tend to disappear using rem for responsive. I would like an option to avoid converting border values if the value is 1px. Something like border-safe ?

I made a quick change locally for one project, it seems to work but i'm sure it can be better... line 33:
```javascript
if(decl.prop === 'border' || decl.prop === 'border-top' || decl.prop === 'border-bottom' || decl.prop === 'border-left' || decl.prop === 'border-right')
{
    if(value.indexOf('1px') >= 0 && value.indexOf('11px') == -1)
    {
        return;
    }
}

```

**Comment by sylvainbaronnet** [comment]
I forgot border-width and border-top-width, etc in the exemple

**Comment by hzlzh** [comment]
check here https://github.com/cuth/postcss-pxtorem/pull/18

**Comment by cuth** [comment]
11f04b09d3616f85f6705567fd30b70e37c9aa7d
