### ISSUE TITLE
selector_black_list - regex match, not a strict one.

### ISSUE THREAD

**Issue by MaxYari** [cuth/postcss-pxtorem#21]
strings from `selector_black_list` are [checked](https://github.com/cuth/postcss-pxtorem/blob/master/index.js#L73) against selector itself using `match` for `regex` which produces not strict comparison. So in attemp to leave `font-size` declared on `body` unchanged, selector like `.post_body` will also be matched.
I suppose it is worth mentioning in readme, that this values are, in fact, producing non-strict `indexOf`-like comparison, or changing to strict comparison in source?

**Comment by cuth** [comment]
I've explained the selectorBlackList matching better in the readme in this commit:

https://github.com/cuth/postcss-pxtorem/commit/a4ed727f75a6cde519fcdd6210a3db069cc62b9c
