### ISSUE TITLE
How about inline-CSS in HTML files?

### ISSUE THREAD

**Issue by hzlzh** [cuth/postcss-pxtorem#22]

**Comment by cuth** [comment]
That would be outside the scope of this project. This is only meant to be a PostCSS plugin. You could create another project that runs all inline styles through PostCSS.

**Comment by hzlzh** [comment]
@cuth thx, I've make https://github.com/weixin/posthtml-px2rem based on [posthtml](https://github.com/posthtml/posthtml)

**Comment by cuth** [comment]
:+1:

**Comment by hopkinson** [comment]
how about .vue . i dont know how to deal with

**Comment by hudhudhud** [comment]
> how about .vue . i dont know how to deal with

have you solve it , i had it too
