### ISSUE TITLE
Consider blacklisting the HTML element?

### ISSUE THREAD

**Issue by furzeface** [cuth/postcss-pxtorem#24]
Hey,

We've encountered an issue with this task when we set our `html` element to have a base `font-size` (of `18px` for example) - for the rest of the styles to inherit from. 

The task runs on the html's CSS and converts its value to a rem unit based against the `rootValue` in the config (18), changing it to `1rem`. 

This then causes it to be `16px` (browser default) and the other elements on the page that have been converted to rem units are sized relatively according to a `16px` base size instead of the `18px` that we want.

Is there a way to exclude the html root element - could that be a best practise going forward? 

Or is there any advice you can give us if we are using this wrong? Currently we're ignoring the html element's CSS by putting px value in capitals as you suggest: `html { font-size: 18PX;}`.

Anything I can do to help let me know,
thanks.

**Comment by cuth** [comment]
Does the `selectorBlackList` option solve your problem?

```js
{
    selectorBlackList: [/^html$/]
}
```

**Comment by JounQin** [comment]
@cuth RegExp can not be used in `package.json`, anyway to achieve this?

**Comment by cuth** [comment]
@JounQin, yeah, that's a problem I didn't think about. Let's open an issue.
