### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [cuth/postcss-pxtorem#3]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by cuth** [comment]
Updated to the postcss 4.1 plugin guidelines.

postcss-pxtorem 2.1.0

**Comment by cuth** [comment]
Linking to the commit: 17d861f

**Comment by TrySound** [comment]
Thanks!
