### ISSUE TITLE
propWhiteList is not working for me

### ISSUE THREAD

**Issue by alexpi** [cuth/postcss-pxtorem#30]
Hello,

My issue is that pxtorem converts only font-related properties to rem, as stated in the docs. I am using the propWhiteList to add for example margin and padding, but I get px values.

I am using a postcss.json file for my config:

```
{
  "use": ["postcss-import",
        "autoprefixer",
        "postcss-pxtorem",
        "postcss-simple-vars",
        "postcss-extend",
        "postcss-nested",
        "postcss-flexbugs-fixes"
     ],
  "css-import": {
    "from": "src/css/"
  },
    "autoprefixer": {
      "browsers": "> 5%"
  },
    "pxtorem": {
        "rootValue": 16,
        "unitPrecision": 5,
        "propWhiteList": ["margin", "padding"],
        "selectorBlackList": [],
        "replace": true,
        "mediaQuery": true
    }
}
```

Any ideas?

**Comment by cuth** [comment]
I've never used a postcss.json file so I can't tell if you've used the correct syntax there.

As for the `postcss-pxtorem` options: You've only included "margin" and "padding" in the `propWhiteList` so only those two properties will be converted. This does not include "margin-left" or "font-size" as you've have to add those as well.

**Comment by freonirons409** [comment]
Same here, doesnt convert margins or padding or anything but fonts even if I specificy margin-top, margin-left, padding-left, etc.

**Comment by cuth** [comment]
@freonirons409, I'll fix if you provide a failing test.

**Comment by cuth** [comment]
Version 4.0.0 changes how propList works.
