### ISSUE TITLE
consider propBlackList ?

### ISSUE THREAD

**Issue by rachardking** [cuth/postcss-pxtorem#31]
we need the  features

**Comment by ikitty** [comment]
we need this feature, really . 
In fact, most of time , we wanna all property apply px2rem beside a few property such as `font , font-size`.

so we think `propBlackList` is useful than `propWhitelist` for developer . 

thanks so much .

**Comment by cuth** [comment]
What do you think about #29?

Can you help me test it? Would it serve your needs?

**Comment by cuth** [comment]
Fixed in version 4.0.0
