### ISSUE TITLE
Error installing with Gulp

### ISSUE THREAD

**Issue by TiagoDeSousa** [cuth/postcss-pxtorem#32]
I'm trying to instal this package with gulp but I keep getting the following error:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "postcss-pxtorem" "--save-dev"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! file /Users/Tiago/Desktop/hyperion/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 15:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /Users/Tiago/Desktop/hyperion/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Tiago/Desktop/hyperion/npm-debug.log

Any ideas of what I'm might be doing wrong?
Thanks.

**Comment by cuth** [comment]
This error just means that NPM could not parse the package.json file. Look for a trailing comma at line 15 and remove it.
