### ISSUE TITLE
pxtorem was not worked in .scss file which has @import .scss file

### ISSUE THREAD

**Issue by xinconan** [cuth/postcss-pxtorem#38]
When I used pxtorem, It was worked in pure scss files, but it was not worked when the scss file import other scss files.How to fix it?
There is the webpack.config.js:
```
loaders: [
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader!postcss')
 }],
postcss: [
        autoprefixer({browsers: ['last 5 versions']}),
        pxtorem({rootValue: 100, propWhiteList: []})
]
```

**Comment by cuth** [comment]
Try using `postcss-loader` instead of `postcss`: https://github.com/postcss/postcss-loader?

**Comment by xinconan** [comment]
I have fixed it, the `postcss` should be placed before the `sass-loader`。
```javascript
{
    test: /\.scss$/,
    loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!postcss!sass-loader')
 }
```

**Comment by lilywang711** [comment]
@xinconan 请问你的 webpack 是怎么配置的呢？我是在 vue中使用这个插件，但是无论如何都配置不成功。如图：
![image](https://user-images.githubusercontent.com/17040010/38603058-21c68e7c-3d9f-11e8-940d-b4f159515fdf.png)
![image](https://user-images.githubusercontent.com/17040010/38603087-3434996e-3d9f-11e8-888a-98afaef4ef2d.png)
