### ISSUE TITLE
Support for custom properties

### ISSUE THREAD

**Issue by methodev** [cuth/postcss-pxtorem#48]
Is it possible to transform values of custom properties as well? For example to switch them on like so:

```
{
    propList: [
        'font',
        'font-size',
        'line-height',
        'letter-spacing',
        '--'
    ]
}
```

**Comment by cuth** [comment]
Ah, this would be a great feature.

**Comment by cuth** [comment]
We can use the wildcard to support custom variables: `propList: ["--*"]`

https://github.com/cuth/postcss-pxtorem/blob/e1467ab371fc1838759febb94789151de1a83ca5/spec/pxtorem-spec.js#L56
