### ISSUE TITLE
Add ability to black list selectors

### ISSUE THREAD

**Issue by spacedawwwg** [cuth/postcss-pxtorem#5]
Would be nice to add the ability to black list selectors. A use case would be `:before` and `:after` in IE9, IE10 do not like using rem's in `line-height`

Being able to black list psuedo elements would allow a work around.

**Comment by mars-abd** [comment]
It will be good to have ability to ignore some properties locally (not all properties by name), may be by comments, I don't know how

**Comment by cuth** [comment]
Right now a good trick is to use an uppercase letter in the "px" since the match is case sensitive.

```css
a {
  font-size: 12Px;
}
```

This would be ignored by pxtorem and still work in all browsers.

**Comment by mars-abd** [comment]
It's a little bit unobviously, but it is good!
I think it should be added to readme docs.

**Comment by cuth** [comment]
You are correct. That needs to happen.

**Comment by cuth** [comment]
I've added a paragraph to the README about ignoring declarations with uppercase `px`.
