### ISSUE TITLE
mediaQuery is not working for me

### ISSUE THREAD

**Issue by sunsl516** [cuth/postcss-pxtorem#50]
hello,
       the option "mediaQuery" is not working in my css code, i  set it to false but the style in media query is still being converted.Here is my setting:

```js
{
      rootValue: 100,
      unitPrecision: 5,
      propList: ['*'],
      selectorBlackList: [],
      replace: true,
      mediaQuery: false,
      minPixelValue: 5
    }
```

**Comment by liu-dongyu** [comment]
+1. Any solution ?

**Comment by cuth** [comment]
Sorry that's not what that option is for. Is only for turning on and off replacing `px`inside the actual media selector:

```
@media only screen and (max-width: 600px)
```

The only thing you can do currently is to capitalize the P in px and it will be ignored.
