### ISSUE TITLE
How to use in angular project?

### ISSUE THREAD

**Issue by vinceok** [cuth/postcss-pxtorem#52]
Help!!!

**Comment by cuth** [comment]
It shouldn't be any problem to use with Angular. You should be able to use it like any other PostCSS plugin.

I believe Angular is just a runtime framework so you might not have added a compile step to your build process yet. PostCSS typically runs on your CSS files before you deploy them. I'd look into Webpack or PostCSS CLI to create a script to run on your CSS files first.
